# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Desktop\Rodrigo\Programs\Horarios\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5.QtCore import QObject, pyqtSlot
from dialog2 import Ui_Dialog2
import sys
from BackLog import BackLog
import os.path

class Ui_Dialog(QWidget):
    
   
    def setupUi(self,Dialog):
        self.Dialog = Dialog 
        self.backlog = BackLog()
        self.configuration = self.backlog.getConfiguration()
        self.Dialog.setObjectName("Dialog")
        self.Dialog.resize(564, 375)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 0, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.Dialog)
        self.pushButton.setGeometry(QtCore.QRect(420, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 120, 311, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 200, 311, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 180, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 200, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 340, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton.clicked.connect(self.openFileNameDialog)
        self.pushButton_2.clicked.connect(self.openFileNameDialogExcel)
        self.label_4 = QtWidgets.QLabel(self.Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 240, 240, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 270, 311, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 270, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3.clicked.connect(self.window2)
        self.pushButton_4.clicked.connect(self.openFileNameDialogDir)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome to SenderS1"))
        self.pushButton.setText(_translate("Dialog", "Browse"))
        self.lineEdit.setText(_translate("Dialog", "config.txt"))
        self.label_2.setText(_translate("Dialog", "Choose the Config File"))
        self.lineEdit_2.setText(_translate("Dialog", "sheet.xls"))
        self.lineEdit_3.setText(_translate("Dialog", "/Directory/"))
        self.label_3.setText(_translate("Dialog", "Choose the Excel File"))
        self.label_4.setText(_translate("Dialog", "Choose the Directory of the Attachments"))
        self.pushButton_2.setText(_translate("Dialog", "Browse"))
        self.pushButton_3.setText(_translate("Dialog", "Submit"))
        self.pushButton_4.setText(_translate("Dialog", "Browse"))
    
    def openFileNameDialog( self ):
        _translate = QtCore.QCoreApplication.translate
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getOpenFileName(self,"Open Text File", "","Just text(*.txt)", options=options)
        if fileName:
            self.configuration['config'] = fileName
            self.backlog.setConfiguration(self.configuration)
            self.lineEdit.setText(_translate("Dialog",fileName))
            
            
    def window2(self):
        
        existsConfig = os.path.isfile(self.lineEdit.text())
        existsExcel = os.path.isfile(self.lineEdit_2.text())
        existsDir = os.path.isdir(self.lineEdit_3.text())
        
        if ( existsConfig == True and existsExcel == True and existsDir == True ):
        
            self.window = QtWidgets.QMainWindow()                                    
            self.w = Ui_Dialog2()
            self.Dialog.hide()
            self.w.setupUi(self.window,self.backlog)
            self.window.show()
        else:
            msg = QtWidgets.QMessageBox.about(self,'Error','Something went wrong. \nPlease verify if the directory, excel and config files are correct')
  
            
    def openFileNameDialogExcel( self ):
        _translate = QtCore.QCoreApplication.translate
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getOpenFileName(self,"Open Excel File", "","Just XLSX Files(*.xlsx)", options=options)
        if fileName:
            self.configuration['sheet'] = fileName
            self.backlog.setConfiguration(self.configuration)
            self.lineEdit_2.setText(_translate("Dialog",fileName))        
            
             
    def openFileNameDialogDir( self ):
        _translate = QtCore.QCoreApplication.translate
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName = str(QFileDialog.getExistingDirectory(self,"Choose the Directory",  options=options))
        if fileName:
            self.configuration['dir'] = fileName
            self.backlog.setConfiguration(self.configuration)
            self.lineEdit_3.setText(_translate("Dialog",fileName))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
